### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [monberin/homework_project_2020#1]
Парсити сайти добре але можна отримати результати з помилками. Зверніть увагу на https://www.gutenberg.org/ https://languages.oup.com/ https://www.sketchengine.eu/.
Рахувати слова, лематизація це дуже просто. Треба ще щось думати робити. Подивіться тут що роблять з поезією https://aclanthology.coli.uni-saarland.de/

Тема: Аналіз поетичних текстів.

**Comment by monberin** [comment]
Я також планую аналізувати твори за позитивною/негативною тональністю, чи буде цього достатньо? Для цього планую використовувати дані з SentiWordNet або аналогічні до них.

**Comment by anrom7** [comment]
SetiWordNet дає тональність окремих слів і тональність твору порахувати не вийде. Також тональність всього твору рахувати не знаю чи варто. Одне речення чи строфа можуть мати позитивну тональність а інша негативну.  Хоча можна знайти багато описів по визначенню тональностей творів.

**Comment by monberin** [comment]
Не могли б Ви будь-ласка підказати можливі напрямки дослідження? Бо з тих матеріалів, що я переглядала, я не впевнена, що саме буде мені посильним.

**Comment by anrom7** [comment]
Вам все до снаги. Отримати поетичні твори Ви можете. Або беріть готові з Gutenberg, або на тріал версії sketchengine генеруєте дані й вони вже будуть і поділені на слова і буде морфологія до кожного слова. Далі заглядаєте у  https://www.aclweb.org/anthology/ Читаєте що роблять з поезією. Наприклад, https://www.aclweb.org/anthology/W12-2502.pdf чи https://www.aclweb.org/anthology/W19-4702.pdf  Це вже щось складніше https://www.aclweb.org/anthology/W15-3703.pdf
Цікаве побачив таке https://www.aclweb.org/anthology/W15-0708.pdf  https://sparsar.wordpress.com/

Читаєте. Обираєте що розумієте як запрограмувати - програмуєте.

**Comment by monberin** [comment]
Дуже дякую, буду рухатись у тому напрямку.
